// src/report.rs
use std::fs::File;
use std::io::Write;


pub fn generate(scan_target: &str) {
    let report_content = format!(r#"
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Iron-Breaker Report: {}</title>
        <style>
            body {{ background-color: #0d1117; color: #c9d1d9; font-family: 'Courier New', monospace; padding: 20px; }}
            h1 {{ color: #58a6ff; text-align: center; border-bottom: 1px solid #30363d; padding-bottom: 10px; }}
            .card {{ background-color: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 15px; margin-bottom: 20px; }}
            .success {{ color: #3fb950; font-weight: bold; }}
            .warning {{ color: #d29922; }}
            a {{ color: #58a6ff; text-decoration: none; border: 1px solid #30363d; padding: 5px 10px; border-radius: 5px; }}
            a:hover {{ background-color: #30363d; }}
        </style>
    </head>
    <body>
        <h1>🛡️ Iron-Breaker Scan Report</h1>
        
        <div class="card">
            <h2>📡 Scan Target: <span style="color: #fff;">{}</span></h2>
            <p>Status: <span class="success">Completed Successfully</span></p>
            <p>Intelligence Provider: <span class="warning">Groq AI (Llama-3)</span></p>
        </div>
        
        <div class="card">
            <h2>📂 Intelligence Data</h2>
            <p>The AI brain has analyzed the server banners and identified potential vulnerabilities.</p>
            <br>
            <a href="ai_reports.txt" target="_blank">📄 Open Full AI Security Report</a>
            <br><br>
            <p style="font-size: 0.9em; color: #8b949e;">(Raw data saved in local directory as 'ai_reports.txt')</p>
        </div>
        
        <footer style="text-align: center; margin-top: 50px; color: #8b949e; font-size: 0.8em;">
            Generated by Iron-Breaker Security Tool
        </footer>
    </body>
    </html>
    "#, scan_target, scan_target);

    
    if let Ok(mut file) = File::create("scan_report.html") {
        let _ = file.write_all(report_content.as_bytes());
        println!("\n    [+] Dashboard Generated Successfully: scan_report.html 📊");
    } else {
        println!("\n    [!] Failed to generate report file.");
    }
}
